spring:
  rabbitmq:
    host: 192.168.220.2
    port: 5672
    username: admin
    password: 123456
    # 消息确认机制 生产者 -> 交换机
    publisher-confirms: true
    # 消息返回机制  交换机 -> 队列
    publisher-returns: true
    # 手动消息确认
    listener:
      simple:
        acknowledge-mode: manual