spring:
  datasource:
    url: jdbc:mysql://sh-cynosdbmysql-grp-ar201mbc.sql.tencentcdb.com:21857/test?useSSL=false&characterEncoding=UTF-8&&serverTimezone=Asia/Shanghai
    username: root
    password: Lzc906159
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**.xml
