spring:
  datasource:
    url: jdbc:mysql://${MYSQL_IP}:3306/test?useSSL=false&characterEncoding=UTF-8&&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**.xml
