spring:
  datasource:
    url: jdbc:mysql://34.92.244.82:3306/test?useSSL=false&characterEncoding=UTF-8&&serverTimezone=Asia/Shanghai
    username: root
    password: xxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/**.xml
