spring:
  redis:
    database: 1
    host: 192.168.3.19
    port: 6379
    password: 123456
    timeout: 3000
  datasource:
      url: jdbc:mysql://sh-cynosdbmysql-grp-ar201mbc.sql.tencentcdb.com:21857/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: xxxxx
      driver-class-name: com.mysql.cj.jdbc.Driver
