spring:
  datasource:
    url: jdbc:mysql://34.126.70.214:3306/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: xxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 最大连接数，默认 10
      maximum-pool-size: 30
mybatis:
  mapper-locations: classpath:mapper/**.xml
